### ISSUE TITLE
Mongodb data not captured

### ISSUE THREAD

**Issue by fdipilla** [newrelic-experimental/newrelic-nestjs-integration#4]
I can see the transactions correctly
![image](https://user-images.githubusercontent.com/4812260/209891800-02ed3da3-7e6d-4c51-a2e3-dde3fcd84e6a.png)

But when I go to `Databases` I don't see anything:
![image](https://user-images.githubusercontent.com/4812260/209891887-f7b3a861-aee0-4e85-8899-9fc693c8f04d.png)

Is this correct? Or there is some miss configuration from my part?

**Comment by matewilk** [comment]
Hey @fdipilla 

In order to see the database metrics, I suggest you follow [these steps in the documentation](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new/)

Since this is a dockerized service, you would need to edit its Docker configuration by adding the New Relic Infrastructure agent and the `nri-mongodb3` integration with its appropriate [configuration](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new/#configuration).
Looking at the docs it might also require changing the `mongodb` image by switching it to an image that is able to deploy a database cluster.

**Comment by fdipilla** [comment]
Thanks for the response! Will check on that. Closing the issue for now until something else comes up
